### ISSUE TITLE
eglMakeCurrent:866 error 3002 (EGL_BAD_ACCESS)

### ISSUE THREAD

**Issue by agnoam** [d-silveira/flutter-share#1]
Hi,
I tried this plugin and on code its look wonderful. but when I tried this in real device its make an exception, and I don't know how to fix it.

my code is:
    	
    // Core
	import 'package:flutter/material.dart';

	// Plugins
	import 'package:share/receive_share_state.dart';
	import 'package:share/share.dart';

	class ShareServices extends StatefulWidget {
	  static const String routeName = '/share';

	  ShareServices({Key key}) : super(key: key);

	  @override
	  _ShareServicesState createState() => new _ShareServicesState();
	}

	class _ShareServicesState extends ReceiveShareState<ShareServices> {

	  @override
	  void receiveShare(Share shared) {
		// TODO: implement receiveShare
		print('shared mimeType is: ${shared.mimeType}');
	  }

	  @override
	  Widget build(BuildContext context) {
		// TODO: implement build
		return Scaffold(
		  appBar: AppBar(title: new Text('Share to'))
		);
	  }
	}

this code compile without any error.
but after the sharing of an image for example I have this exception:

    E/libEGL  (28713): eglMakeCurrent:866 error 3002 (EGL_BAD_ACCESS)
	E/flutter (28713): [ERROR:flutter/shell/platform/android/android_context_gl.cc(217)] Could not make the context current
	E/flutter (28713): [ERROR:flutter/shell/platform/android/android_context_gl.cc(53)] EGL Error: EGL_BAD_ACCESS (12290)
	I/FlutterActivityDelegate(28713): onResume setting current activity to this
	E/BpSurfaceComposerClient(28713): Failed to transact (-1)
	E/BpSurfaceComposerClient(28713): Failed to transact (-1)

My Flutter Doctor is: 
	
    C:\flutter\bin\flutter.bat --no-color doctor
	Doctor summary (to see all details, run flutter doctor -v):
	[√] Flutter (Channel beta, v0.4.4, on Microsoft Windows [Version 10.0.16299.431], locale he-IL)
	[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
	[√] Android Studio (version 3.1)
	[√] VS Code, 64-bit edition (version 1.23.1)
	[√] Connected devices (1 available)

	• No issues found!
	Process finished with exit code 0

**Comment by d-silveira** [comment]
Does this happen always, I mean is it easy to reproduce, and does it crash your application?

**Comment by agnoam** [comment]
My app not crash. This happen every time that I click on the Share button.

**Comment by agnoam** [comment]
Hey @d-silveira there is something new ?

**Comment by d-silveira** [comment]
I don't know why we get that GL exception, but I just tried creating a new flutter project from scratch, and also with your example. These are my conclusions:
1. the README is missing an important step, which is calling ``enableShareReceiving();`` in initState
2. the EGL Error is always logged, and has no impact

So I'm going to fix the README and close this issue
