### ISSUE TITLE
The following MissingPluginException was thrown while activating platform stream on channel

### ISSUE THREAD

**Issue by agnoam** [d-silveira/flutter-share#2]
I/flutter ( 6676): ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
	I/flutter ( 6676): The following MissingPluginException was thrown while activating platform stream on channel
	I/flutter ( 6676): plugins.flutter.io/receiveshare:
	I/flutter ( 6676): MissingPluginException(No implementation found for method listen on channel
	I/flutter ( 6676): plugins.flutter.io/receiveshare)
	I/flutter ( 6676): 
	I/flutter ( 6676): When the exception was thrown, this was the stack:
	I/flutter ( 6676): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:278:7)
	I/flutter ( 6676): <asynchronous suspension>
	I/flutter ( 6676): #1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:418:29)
	I/flutter ( 6676): <asynchronous suspension>
	I/flutter ( 6676): #6      ReceiveShareState.enableShareReceiving (package:share/receive_share_state.dart:23:43)
	I/flutter ( 6676): #7      _AppRootState.build (file:///Flutter%20Workspace/digital_frame/lib/main.dart:87:5)
	I/flutter ( 6676): #8      StatefulElement.build (package:flutter/src/widgets/framework.dart:3730:27)
	I/flutter ( 6676): #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3642:15)
	I/flutter ( 6676): #10     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
	I/flutter ( 6676): #11     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
	I/flutter ( 6676): #12     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
	I/flutter ( 6676): #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
	I/flutter ( 6676): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
	I/flutter ( 6676): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
	I/flutter ( 6676): #16     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:857:16)
	I/flutter ( 6676): #17     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:828:5)
	I/flutter ( 6676): #18     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:774:17)
	I/flutter ( 6676): #19     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2222:19)
	I/flutter ( 6676): #20     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:773:13)
	I/flutter ( 6676): #21     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:662:7)
	I/flutter ( 6676): #22     runApp (package:flutter/src/widgets/binding.dart:704:7)
	I/flutter ( 6676): #23     main.<anonymous closure> (file:////Flutter%20Workspace/digital_frame/lib/main.dart:55:7)
	I/flutter ( 6676): #30     StorageH.getJSON (package:digital_frame/services/storage.services.dart)
	I/flutter ( 6676): <asynchronous suspension>
	I/flutter ( 6676): #31     main (file:// Flutter%20Workspace/digital_frame/lib/main.dart:39:14)
	I/flutter ( 6676): <asynchronous suspension>
	I/flutter ( 6676): #32     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
	I/flutter ( 6676): #33     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
	I/flutter ( 6676): (elided 10 frames from package dart:async)
	I/flutter ( 6676): ════════════════════════════════════════════════════════════════════════════════════════════════════

Anyone know why that happen ?

**Comment by d-silveira** [comment]
Hey @agnoam,
I seems that the plugin is not gettting recognized yet.
After you added the dependency to pubspec try to run flutter clean; flutter packages get, maybe close android-studio and reopen it 
Please let me know hoe it goes

**Comment by agnoam** [comment]
Did it and stay the same.

**Comment by agnoam** [comment]
Hey @d-silveira there is something new ?

**Comment by d-silveira** [comment]
Hey @agnoam I didn't have time yet to try and reproduce this bug, because I've been busy with something else.
As soon as I get the chance, probably next week, I'll check it out, to see what is going on. 
I'll keep you posted.

**Comment by agnoam** [comment]
@d-silveira You have some good news ?

**Comment by agnoam** [comment]
Whats going with your plugin ?

**Comment by agnoam** [comment]
Hey @d-silveira you already tried to fix it ?

**Comment by d-silveira** [comment]
I Just created a new Flutter project from scratch, followed the README and never could reproduce this issue, please make sure you follow every step. Keep in mind, that the README was missing one step to enableReceiving of shares
