### ISSUE TITLE
iOS share receive still being worked on?

### ISSUE THREAD

**Issue by bgh80** [d-silveira/flutter-share#23]
Is receiving intents on iOS still being worked on? Specifically, receiving file share intents. Just after a quick update on the status of this project.

**Comment by r0ck3r** [comment]
Looking for this too

**Comment by magnuswikhog** [comment]
I'm looking for this as well.

**Comment by lifenautjoe** [comment]
Seems like the library is unfortunately dead.

**Comment by lifenautjoe** [comment]
@d-silveira , any chance on this happening? We would be willing to sponsor some of your work hours on this!

**Comment by d-silveira** [comment]
Hi everyone, sorry, these emails were going unnoticed. In iOS there are several issues, and having not enough time, And not having the help needed to stabilize the iOS part, I didn't come looking for this code.
Now seeing all the interest that it currently has, I'll try to make some time to merge pull requests at least and start triaging issues.

thanks for your interest,
Regards
