### ISSUE TITLE
Share PDF files

### ISSUE THREAD

**Issue by gglazer** [d-silveira/flutter-share#4]
Hello,
I'd like to share PDF files with another apps (both on Android and iOS).
Could you give me an example to use `Share.file(path: <String>, mimeType: ShareType, title: , text: );`?
These files are in app's download directory.
Thanks in advance!

**Comment by d-silveira** [comment]
Currently only Android is working for file sharing.
You'll need to use a [documents picker](https://pub.dartlang.org/packages/documents_picker) and, upon selection of the document, you'll receive it's path, which you can then use to the Share.file() constructor, the mimeType should be set to ShareType.TYPE_FILE, title and text are optional.
Forewarning, @pablote discovered an [issue with permissions](https://github.com/d-silveira/flutter-share/issues/5) which might affect you once you are finally able to share the file.
